/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerSettingsRouteImport } from './routes/seller.settings'
import { Route as SellerOnboardingRouteImport } from './routes/seller.onboarding'
import { Route as SellerEarningsRouteImport } from './routes/seller.earnings'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as SellerAgentsNewRouteImport } from './routes/seller.agents.new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSettingsRoute = SellerSettingsRouteImport.update({
  id: '/seller/settings',
  path: '/seller/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOnboardingRoute = SellerOnboardingRouteImport.update({
  id: '/seller/onboarding',
  path: '/seller/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerEarningsRoute = SellerEarningsRouteImport.update({
  id: '/seller/earnings',
  path: '/seller/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerAgentsNewRoute = SellerAgentsNewRouteImport.update({
  id: '/seller/agents/new',
  path: '/seller/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/runs': typeof RunsRoute
  '/showcase': typeof ShowcaseRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/agents/new': typeof SellerAgentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/runs': typeof RunsRoute
  '/showcase': typeof ShowcaseRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/agents/new': typeof SellerAgentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof ProfileRoute
  '/runs': typeof RunsRoute
  '/showcase': typeof ShowcaseRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/earnings': typeof SellerEarningsRoute
  '/seller/onboarding': typeof SellerOnboardingRoute
  '/seller/settings': typeof SellerSettingsRoute
  '/seller/agents/new': typeof SellerAgentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/forgot-password'
    | '/profile'
    | '/runs'
    | '/showcase'
    | '/signin'
    | '/signup'
    | '/agents/$slug'
    | '/seller/dashboard'
    | '/seller/earnings'
    | '/seller/onboarding'
    | '/seller/settings'
    | '/seller/agents/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/forgot-password'
    | '/profile'
    | '/runs'
    | '/showcase'
    | '/signin'
    | '/signup'
    | '/agents/$slug'
    | '/seller/dashboard'
    | '/seller/earnings'
    | '/seller/onboarding'
    | '/seller/settings'
    | '/seller/agents/new'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/forgot-password'
    | '/profile'
    | '/runs'
    | '/showcase'
    | '/signin'
    | '/signup'
    | '/agents/$slug'
    | '/seller/dashboard'
    | '/seller/earnings'
    | '/seller/onboarding'
    | '/seller/settings'
    | '/seller/agents/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProfileRoute: typeof ProfileRoute
  RunsRoute: typeof RunsRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerEarningsRoute: typeof SellerEarningsRoute
  SellerOnboardingRoute: typeof SellerOnboardingRoute
  SellerSettingsRoute: typeof SellerSettingsRoute
  SellerAgentsNewRoute: typeof SellerAgentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/settings': {
      id: '/seller/settings'
      path: '/seller/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof SellerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/onboarding': {
      id: '/seller/onboarding'
      path: '/seller/onboarding'
      fullPath: '/seller/onboarding'
      preLoaderRoute: typeof SellerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/earnings': {
      id: '/seller/earnings'
      path: '/seller/earnings'
      fullPath: '/seller/earnings'
      preLoaderRoute: typeof SellerEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/agents/new': {
      id: '/seller/agents/new'
      path: '/seller/agents/new'
      fullPath: '/seller/agents/new'
      preLoaderRoute: typeof SellerAgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProfileRoute: ProfileRoute,
  RunsRoute: RunsRoute,
  ShowcaseRoute: ShowcaseRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerEarningsRoute: SellerEarningsRoute,
  SellerOnboardingRoute: SellerOnboardingRoute,
  SellerSettingsRoute: SellerSettingsRoute,
  SellerAgentsNewRoute: SellerAgentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
